"use client";

import { motion, AnimatePresence } from "framer-motion";
import { useState } from "react";
import { useStore } from "@/lib/store";
import { STYLES, AI_PROMPTS } from "@/lib/constants";
import { Heart, Share2, Download, Check, ArrowRight } from "lucide-react";

export default function ResultsPage({ onNavigate }: { onNavigate: (page: string) => void }) {
  const { outfits, analysis, selectedStyle, uploadedImage, favorites, toggleFavorite, productLink } = useStore();
  const [activeTab, setActiveTab] = useState(0);
  const styleData = STYLES.find((s) => s.id === selectedStyle);

  if (!outfits || !analysis) return null;

  const labels = ["Safe Stylish", "Trendy Bold", "Premium Luxury"];
  const labelIcons = ["🎯", "🔥", "💎"];

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="max-w-[1100px] mx-auto"
      style={{ padding: "40px 24px 100px" }}
    >
      <button
        onClick={() => onNavigate("dashboard")}
        className="bg-transparent border-none cursor-pointer text-sm mb-6 flex items-center gap-1.5"
        style={{ color: "var(--text-muted)" }}
      >
        ← Back to Dashboard
      </button>

      {/* Header */}
      <div className="flex items-start justify-between flex-wrap gap-4 mb-9">
        <div>
          <h1 className="font-serif font-normal mb-2" style={{ fontSize: "clamp(28px, 4vw, 38px)" }}>
            Your <span className="gradient-text" style={{ fontStyle: "italic" }}>{styleData?.label}</span> outfits
          </h1>
          <p className="text-sm" style={{ color: "var(--text-muted)" }}>
            3 variations generated by AI — tap to explore each look
          </p>
        </div>
        <button className="btn-primary !py-3 !px-7 !text-sm" onClick={() => onNavigate("dashboard")}>
          Generate Again
        </button>
      </div>

      {/* ═══ BEFORE / AFTER — SIDE BY SIDE ═══ */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        className="grid grid-cols-1 md:grid-cols-2 gap-5 mb-8"
      >
        {/* BEFORE — Original Photo */}
        <div
          className="rounded-[20px] overflow-hidden relative"
          style={{ border: "1px solid var(--border)", background: "var(--bg-card)" }}
        >
          <div
            className="px-4 py-3 text-xs font-bold uppercase tracking-[2px] text-center"
            style={{ background: "var(--surface)", color: "var(--text-muted)", borderBottom: "1px solid var(--border)" }}
          >
            📷 Original Photo
          </div>
          {uploadedImage && (
            <div className="p-4 flex justify-center">
              <img
                src={uploadedImage}
                alt="Original"
                className="rounded-2xl object-cover"
                style={{ maxHeight: 400, width: "100%" }}
              />
            </div>
          )}
        </div>

        {/* AFTER — AI Styled Outfit */}
        <div
          className="rounded-[20px] overflow-hidden relative"
          style={{ border: "2px solid var(--accent)", background: "var(--bg-card)" }}
        >
          <div
            className="px-4 py-3 text-xs font-bold uppercase tracking-[2px] text-center text-white"
            style={{ background: "linear-gradient(135deg, var(--gradient-1), var(--gradient-2))" }}
          >
            ✨ AI Styled — {outfits[activeTab]?.name}
          </div>
          <div className="p-5">
            {/* Outfit visual representation */}
            <div className="rounded-2xl p-6 mb-4 relative overflow-hidden" style={{ background: "var(--surface)", minHeight: 280 }}>
              {/* Color atmosphere */}
              <div className="absolute inset-0 opacity-20" style={{
                background: `linear-gradient(135deg, ${outfits[activeTab]?.colors?.[0] || '#333'}44, ${outfits[activeTab]?.colors?.[1] || '#666'}44, ${outfits[activeTab]?.colors?.[2] || '#999'}44)`,
              }} />

              {/* Outfit breakdown visual */}
              <div className="relative z-10 space-y-4">
                <div className="text-center mb-5">
                  <div className="font-serif text-2xl mb-1">{outfits[activeTab]?.name}</div>
                  <div className="text-sm" style={{ color: "var(--text-muted)" }}>{outfits[activeTab]?.description || `${labels[activeTab]} variation`}</div>
                </div>

                {/* Garment cards */}
                {[
                  { label: "TOP", value: outfits[activeTab]?.top, emoji: "👕" },
                  { label: "BOTTOM", value: outfits[activeTab]?.bottom, emoji: "👖" },
                  { label: "SHOES", value: outfits[activeTab]?.shoes, emoji: "👟" },
                ].map((item, i) => (
                  <div key={i} className="flex items-start gap-3 rounded-xl p-3" style={{ background: "var(--bg-card)", border: "1px solid var(--border)" }}>
                    <span className="text-xl mt-0.5">{item.emoji}</span>
                    <div>
                      <div className="text-[10px] font-bold uppercase tracking-[1.5px] mb-0.5" style={{ color: "var(--accent)" }}>{item.label}</div>
                      <div className="text-sm leading-snug">{item.value}</div>
                    </div>
                  </div>
                ))}

                {/* Accessories inline */}
                <div className="flex items-start gap-3 rounded-xl p-3" style={{ background: "var(--bg-card)", border: "1px solid var(--border)" }}>
                  <span className="text-xl mt-0.5">💍</span>
                  <div>
                    <div className="text-[10px] font-bold uppercase tracking-[1.5px] mb-0.5" style={{ color: "var(--accent)" }}>ACCESSORIES</div>
                    <div className="text-sm leading-snug">{outfits[activeTab]?.accessories?.join(" · ") || "—"}</div>
                  </div>
                </div>
              </div>
            </div>

            {/* Color palette */}
            <div className="flex items-center gap-3">
              <div className="text-[10px] font-bold uppercase tracking-[1px]" style={{ color: "var(--text-dim)" }}>Palette</div>
              <div className="flex gap-2">
                {outfits[activeTab]?.colors?.map((c: string, i: number) => (
                  <div key={i} className="flex items-center gap-1.5">
                    <div className="w-6 h-6 rounded-lg" style={{ background: c, border: "1px solid var(--border)" }} />
                    <span className="font-mono text-[10px]" style={{ color: "var(--text-dim)" }}>{c}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </motion.div>

      {/* ═══ AI ANALYSIS CARD ═══ */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.15 }}
        className="rounded-[18px] p-6 mb-8"
        style={{ background: "var(--bg-card)", border: "1px solid var(--border)" }}
      >
        <div className="text-[13px] font-semibold uppercase tracking-[1.5px] mb-3.5" style={{ color: "var(--accent)" }}>
          🧠 AI Analysis Results
        </div>
        <div className="grid gap-4" style={{ gridTemplateColumns: "repeat(auto-fit, minmax(130px, 1fr))" }}>
          {[
            { label: "Skin Tone", value: analysis.skinTone },
            { label: "Undertone", value: analysis.undertone },
            { label: "Face Shape", value: analysis.faceShape },
            { label: "Body Type", value: analysis.bodyType },
            { label: "Hair", value: analysis.hairColor },
            { label: "Confidence", value: `${analysis.confidence}%` },
          ].map((item, i) => (
            <div key={i}>
              <div className="text-[11px] uppercase tracking-[1px] mb-1" style={{ color: "var(--text-dim)" }}>{item.label}</div>
              <div className="text-[15px] font-semibold">{item.value}</div>
            </div>
          ))}
        </div>
      </motion.div>

      {/* ═══ OUTFIT VARIATION TABS ═══ */}
      <div className="flex gap-2 mb-6 flex-wrap">
        {outfits.map((_: any, i: number) => (
          <button
            key={i}
            onClick={() => setActiveTab(i)}
            className="flex items-center gap-1.5 px-5 py-2.5 rounded-xl cursor-pointer text-sm font-semibold transition-all duration-200"
            style={{
              border: `1px solid ${activeTab === i ? "var(--accent)" : "var(--border)"}`,
              background: activeTab === i ? "var(--accent-dim)" : "var(--bg-card)",
              color: activeTab === i ? "var(--accent)" : "var(--text-muted)",
            }}
          >
            {labelIcons[i]} {labels[i]}
          </button>
        ))}
      </div>

      {/* ═══ DETAILED OUTFIT CARD ═══ */}
      <AnimatePresence mode="wait">
        <motion.div
          key={activeTab}
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -8 }}
          className="rounded-[22px] overflow-hidden"
          style={{ background: "var(--bg-card)", border: "1px solid var(--border)" }}
        >
          <div style={{ padding: "28px 32px" }}>
            {/* Title + actions */}
            <div className="flex justify-between items-center mb-6">
              <div>
                <div className="font-serif text-[26px] font-normal">{outfits[activeTab]?.name}</div>
                <div className="text-[13px] mt-1" style={{ color: "var(--text-muted)" }}>
                  {labels[activeTab]} variation · {styleData?.label} style
                  {outfits[activeTab]?.occasion && <> · Best for: {outfits[activeTab].occasion}</>}
                </div>
              </div>
              <div className="flex gap-2">
                <button onClick={() => toggleFavorite(`${activeTab}-${selectedStyle}`)}
                  className="w-10 h-10 rounded-[10px] flex items-center justify-center cursor-pointer border-none"
                  style={{ background: "var(--surface)", border: "1px solid var(--border)", color: favorites.has(`${activeTab}-${selectedStyle}`) ? "#E74C3C" : "var(--text-muted)" }}>
                  <Heart size={18} fill={favorites.has(`${activeTab}-${selectedStyle}`) ? "currentColor" : "none"} />
                </button>
                <button className="w-10 h-10 rounded-[10px] flex items-center justify-center cursor-pointer border-none" style={{ background: "var(--surface)", border: "1px solid var(--border)", color: "var(--text-muted)" }}>
                  <Share2 size={18} />
                </button>
                <button className="w-10 h-10 rounded-[10px] flex items-center justify-center cursor-pointer border-none" style={{ background: "var(--surface)", border: "1px solid var(--border)", color: "var(--text-muted)" }}>
                  <Download size={18} />
                </button>
              </div>
            </div>

            {/* Garment grid */}
            <div className="grid gap-4 mb-6" style={{ gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))" }}>
              {[
                { label: "Top", value: outfits[activeTab]?.top },
                { label: "Bottom", value: outfits[activeTab]?.bottom },
                { label: "Shoes", value: outfits[activeTab]?.shoes },
              ].map((item, i) => (
                <div key={i} className="rounded-[14px]" style={{ padding: 18, background: "var(--surface)", border: "1px solid var(--border)" }}>
                  <div className="text-[11px] font-semibold uppercase tracking-[1px] mb-1.5" style={{ color: "var(--accent)" }}>{item.label}</div>
                  <div className="text-sm leading-relaxed">{item.value}</div>
                </div>
              ))}
            </div>

            {/* Accessories */}
            <div className="mb-5">
              <div className="text-[11px] font-semibold uppercase tracking-[1px] mb-2.5" style={{ color: "var(--accent)" }}>Accessories</div>
              <div className="flex gap-2 flex-wrap">
                {outfits[activeTab]?.accessories?.map((a: string, i: number) => (
                  <span key={i} className="px-4 py-2 rounded-[10px] text-[13px]" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>{a}</span>
                ))}
              </div>
            </div>

            {/* Color Palette */}
            <div>
              <div className="text-[11px] font-semibold uppercase tracking-[1px] mb-2.5" style={{ color: "var(--accent)" }}>Color Palette</div>
              <div className="flex gap-3">
                {outfits[activeTab]?.colors?.map((c: string, i: number) => (
                  <div key={i} className="flex flex-col items-center gap-1">
                    <div className="w-12 h-12 rounded-xl" style={{ background: c, border: "1px solid var(--border)" }} />
                    <span className="font-mono text-[10px]" style={{ color: "var(--text-dim)" }}>{c}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </motion.div>
      </AnimatePresence>

      {/* AI Prompt Preview */}
      <details className="mt-8 rounded-2xl overflow-hidden" style={{ background: "var(--bg-card)", border: "1px solid var(--border)" }}>
        <summary className="px-6 py-4 cursor-pointer text-sm font-semibold" style={{ color: "var(--text-muted)" }}>
          View AI Prompt Template Used
        </summary>
        <pre className="font-mono text-xs leading-relaxed whitespace-pre-wrap overflow-auto"
          style={{ padding: "16px 24px", color: "var(--text-dim)", borderTop: "1px solid var(--border)", background: "var(--surface)", maxHeight: 300 }}>
          {AI_PROMPTS.generation({
            skinTone: analysis.skinTone, undertone: analysis.undertone,
            style: styleData?.label || "", bodyType: analysis.bodyType,
            faceShape: analysis.faceShape, hasProduct: !!productLink,
            productDesc: productLink || "uploaded product image",
          })}
        </pre>
      </details>
    </motion.div>
  );
}
